### ISSUE TITLE
undoEntityUpdate may undo the addition of a classification rather than strictly an entity change

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-crux#131]
The current implementation of the `restorePreviousVersionOfEntity` method simply rolls back to the previous version of the entity from Crux's perspective, which may actually be a view of the entity where a classification has been added (or otherwise changed) -- which would not strictly be undoing the last change to the entity itself, since classifications have their own independent lifecycle.

For example, imagine this chronological ordering of activity:

1. Entity E is added (v1).
2. Entity E is updated (v2).
3. Entity E is classified (still v2, but now also has a classification).
4. An `undoEntityUpdate` is called against entity E.

Should we:

- rollback Entity E itself to its v1 set of information (1), but still have the classification from (3) available?
- or rollback Entity E to its v2 set of information (2), where the classification from (3) is no longer available?

**Comment by mandy-chessell** [comment]
@cmgrote I agree with the comment above.  Here is an explanation

* The classification as you state is on an independent lifecycle (in fact other classifications may be stored in a different repository and so can not be part of the undo.
* The version number has to be incremented so that we can properly sequence the events related to the entity.
