### ISSUE TITLE
Store serialised values in a nested sub-map

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-crux#2]
For any values that we store in serialised form to improve their efficient retrieval, store them in a nested sub-map within the document map to avoid them being indexed and potentially used by full-text searches:

```
{
  :crux.db/id :entity/12345
  :entityProperties/Referenceable.qualifiedName.value "my-qualified-name"
  :type {:InstanceType "{\"serialised\": \"json-string\"}"}
}
```

**Comment by grahamwallis** [comment]
@cmgrote I think this is a good approach. I used it in the graph repo, alongside indexing of the individual properties. I have never measured the efficiency scientifically but I am not aware of any disadvantages of doing it. It's useful for collections too, because as you say it offers full text search.

One thing to be careful of is the use of non-alphanumeric separators in property keys (I'm thinking of Referenceable.qualifiedName.value in the example above). The Lucene API is not keen on them.

**Comment by cmgrote** [comment]
Yes, I'm definitely keeping that comment in mind once I get around to the Lucene side of things; however, I suspect it may not present the same problem in this repository as strictly speaking these `:entityProperties/Referenceable.qualifiedName.value` "things" are not actually Strings but Keyword objects (internal references, of sorts), and the query syntax doesn't actually need them to be specified anywhere to search against -- so my initial hope is that they are not actually directly used in the Lucene index as such (I have a hunch they may anyway be translated into hashed values in regards to how they are represented in the Lucene index).  But will certainly keep this top of mind as the first potential issue to explore!

Here's what a query would look like using Lucene, across all attributes (except those that are sub-mapped) -- note that the property names being searched don't actually need to be specified anywhere in such a query:

```
{:find '[?e ?v ?a ?s]
 :where '[[(wildcard-text-search "Iva*") [[?e ?v ?a ?s]]]
 [?e :crux.db/id]]}
```
